sxtblog/blog/urls.py
from django.conf.urls import url, include
from blog import views


app_name = 'blog'
urlpatterns = [
    url('^$', views.index, name='index'),
    url('^blog/(\d*)', views.index),
    url(r'^post/(\d+)', views.post, name='post'),
    url(r'^about/', views.about, name='about'),
    url(r'^category/(\d+)', views.category, name='category'),
    url(r'^archive/(\d+)/(\d+)', views.archive, name='archive'),
    url(r'^search/$', views.search),
]

sxtblog/sxtblog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.static import serve
from sxtblog.settings import MEDIA_ROOT


urlpatterns = [
    url('admin/', admin.site.urls),
    url('^', include('blog.urls', namespace='blog')),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)/$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^search/', include('haystack.urls')),
]
# python manage.py rebuild_index

sxtblog/blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# 种类
class Category(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    cname = models.CharField(max_length=20)

    def __str__(self):
        return self.cname

    class Meta:
        db_table = "t_category"
        verbose_name_plural = '类别'


# 标签
class Tag(models.Model):
    id = models.AutoField(primary_key=True)
    tname = models.CharField(max_length=20)

    def __str__(self):
        return self.tname

    class Meta:
        db_table = "t_tag"
        verbose_name_plural = '标签'


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20, verbose_name='标题')
    desc = models.TextField(verbose_name='简介')
    content = RichTextUploadingField(null=True, blank=True, verbose_name='内容')
    created = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modified = models.DateField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "t_post"
        verbose_name_plural = '帖子'

sxtblog/blog/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render
from .models import *


def get_page(num, size):
    num = int(num)
    paginator = Paginator(Post.objects.all().order_by('-created'), size)
    if num < 1:
        num = 1
    if num > paginator.num_pages:
        num = paginator.num_pages

    # 每次展示的链接数
    a_size = 3
    start = ((num-1)//a_size)*10+1
    end = start + a_size

    # if start < 1:
    #     start = 1
    if end > paginator.num_pages:
        end = paginator.num_pages + 1


    return paginator.page(num), range(start, end)


def index(request, num='1'):
    # 避免不带参数时发生的错误
    if not num:
        num = '1'
    # 每页展示的内容数量
    size = '3'
    posts, page_range = get_page(num, size)
    return render(request, 'index.html', {'posts': posts, 'page_range': page_range})


def post(request, post_id):
    post = Post.objects.get(id=post_id)
    return render(request, 'post.html', {'post': post})


def about(request):
    return HttpResponse('暂时没有')


def category(request, category_id):
    # 找出当前分类的所有博客
    post = Post.objects.filter(category__id=category_id)
    return render(request, 'category.html', {'post': post})


def archive(request, year, month):
    # 方法1 找出当前参数所在时间的所有博客
    post = Post.objects.filter(created__year=year, created__month=month)
    # 方法2
    # post = Post.objects.filter(Q(created__year=year)&Q(created__month=month))
    # 方法3
    # post = Post.objects.filter(created__year=year).filter(created__month=month)
    return render(request, 'archive.html', {'post': post})


# 全文搜索功能
def search(request):
    from haystack.query import SearchQuerySet
    from haystack.query import SQ

    # 获取请求参数
    keywords = request.GET.get('q', '')

    search_posts = SearchQuerySet().filter(SQ(title=keywords)|SQ(content=keywords))

    s_posts = []

    for s_p in search_posts:
        s_posts.append(s_p.object)

    return render(request, 'search.html', {'archive_posts': s_posts})

sxtblog/blog/templates/archive.html
{% extends 'base.html' %}

{% block main %}
    {% for i in post %}
        <div class="archives">
            <article class="archive-article archive-type-post">
                <div class="archive-article-inner">
                    <header class="archive-article-header">
                        <a href="/archive/{{ i.created|date:'Y/m' }}" class="archive-article-date">
                            <time>{{ i.created|date:'Y年m月d日 H:i:s' }}2</time>
                        </a>

                        <h1 itemprop="name">
                            <a class="archive-article-title" target="_blank" href="/post/{{ i.id }}">{{ i.title }}</a>
                        </h1>
                    </header>
                </div>
            </article>
        </div>
    {% endfor %}
{% endblock main %}

sxtblog/blog/templates/category.html
{% extends 'base.html' %}

{% block main %}
    {% for i in post %}
    <article class="archive-article archive-type-post">
        <div class="archive-article-inner">
            <header class="archive-article-header">
                <a href="/archive/{{ i.created|date:'Y/m' }}" class="archive-article-date">
                    <time>{{ i.created|date:'Y年m月d日 H:i:s' }}</time>
                </a>

                <h1 itemprop="name">
                    <a class="archive-article-title" target="_blank" href="/post/{{ i.id }}">{{ i.title }}</a>
                </h1>
            </header>
        </div>
    </article>
    {% endfor %}
{% endblock main %}

sxtblog/blog/templates/index.html
{% extends 'base.html' %}
{#{% load staticfiles %}#}
{% block main %}
    {% for post in posts %}
    <article class="article article-type-post">
        <div class="article-meta">
            <a class="article-date">
                <time><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ post.created|date:'Y-m-d H:i:s ' }}</font></font></time>
            </a>
            <div class="article-category">
                <a class="article-category-link" href="{% url 'blog:category' post.category.id %}" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ post.category }}</font></font></a>
            </div>
        </div>


        <div class="article-inner">
            <header class="article-header">
                <h1 itemprop="name">
                    <a class="article-title" href="/post/{{ post.id }}" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ post.title }}</font></font></a>
                </h1>
            </header>
            <div class="article-entry" itemprop="articleBody">
                <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">前言</font></font></h2>
                <hr><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                {{ post.desc }}

                </font></font><p class="article-more-link">
                    <a href="/post/{{ post.id }}" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">阅读全文</font></font></a>
                </p>
            </div>
            <footer class="article-footer">
                <a data-url="存放文章的url" class="article-share-link"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">分享</font></font></a>
                <ul class="article-tag-list">

                    {% for t in post.tag.all %}
                    <li class="article-tag-list-item">
                        <a class="article-tag-list-link" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ t.tname }}</font></font></a>
                    </li>
                    {% endfor %}

                </ul>
            </footer>
        </div>

    </article>

{% endfor %}


    <nav id="page-nav">


        {% if posts.has_previous %}
            <a class="page-number" href="/blog/{{ posts.previous_page_number }}"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Previou</font></font></a>
        {% endif %}
        {% for page in page_range %}
            {% if page == posts.number %}
                 <a style="color:black; font-weight: bold;" class="page-number" href="/blog/{{ page }}"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ i }}</font></font></a>
            {% else %}
                 <a style="color:blue;" class="page-number" href="/blog/{{ page }}"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ page }}</font></font></a>
            {% endif %}
        {% endfor %}

        {% if posts.has_next%}
            <a class="page-number" href="/blog/{{ posts.next_page_number }}"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Next</font></font></a>
        {% endif %}
    </nav>

{% endblock %}

sxtblog/blog/templates/post.html
{% extends 'base.html' %}
{% block main %}
<article class="article article-type-post">
    <div class="article-meta">
        <a class="article-date">
            <time><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ post.created|date:'Y-m-d H:i:s ' }}</font></font></time>
        </a>
        <div class="article-category">
            <a class="article-category-link" href="http://localhost:8000/#" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ post.category.cname }}</font></font></a>
        </div>
    </div>


    <div class="article-inner">
        <header class="article-header">
            <h1 itemprop="name">
                <a class="article-title" href="/blog/post/21" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ post.title }}</font></font></a>
            </h1>
        </header>
        <div class="article-entry" itemprop="articleBody">
            <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">前言</font></font></h2>
            <hr />
{#            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">#}
{#            {{ post.desc }}#}
{#            <hr />#}
            {{ post.content|safe }}
{#            </font>#}
{#            </font>#}
{#            <p class="article-more-link">#}
{#                <a href="/blog/post/21" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">阅读全文</font></font></a>#}
{#            </p>#}
            <br />
        </div>
        <footer class="article-footer">
            <a data-url="存放文章的url" class="article-share-link"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">分享</font></font></a>
{#            <ul class="article-tag-list">#}
{##}
{#                {% for t in post.tag.all %}#}
{#                <li class="article-tag-list-item">#}
{#                    <a class="article-tag-list-link" href="http://localhost:8000/#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ t.tname }}</font></font></a>#}
{#                </li>#}
{#                {% endfor %}#}
{##}
{#            </ul>#}
        </footer>
    </div>


</article>
{% endblock %}

sxtblog/blog/templates/search.html
{% extends 'base.html' %}

{% block main %}

    {% if archive_posts %}

    <div class="archives">
        {% for archive_post in archive_posts %}

            <article class="archive-article archive-type-post">
              <div class="archive-article-inner">
                <header class="archive-article-header">
                <a href="#" class="archive-article-date">
                     <time>{{ archive_post.created.year }} {{ archive_post.created.month }}</time>
                </a>

                 <h1 itemprop="name">
                      <a class="archive-article-title" target="_blank" href="/post/{{ archive_post.id }}">{{ archive_post.title }}</a>
                 </h1>
                 </header>
              </div>
            </article>

        {% endfor %}

    </div>


    {% else %}

        <div class="archives">
            无记录
         </div>

    {% endif %}

{% endblock main %}

sxtblog/templates/base.html
{% load staticfiles %}
{#{% load static from staticfiles %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人博客</title>
{#    <link rel="stylesheet" href=" /static/css/style.css">#}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        form {
            position: relative;
            width: 150px;
            margin: 0 auto;
        }

        .d1 {
            float: right;
            line-height: 67px;
        }

        .d1 input {
            width: 100px;
            height: 30px;
            border: 2px solid darkred;
            border-radius: 5px;
            outline: none;
            background: white;
            color: #1e242a;
        }
    </style>
</head>
<body>
<div id="container">
    <div id="wrap">
        <header id="header">
            {% include 'header.html'  %}
        </header>
<div class="outer">
    <div id="main">
        {% block main %}

        {% endblock %}

    </div>
<aside id="sidebar">
     {% include 'right.html' %}
</aside>
</div>
        <footer id="footer">
            {% include 'footer.html' %}
        </footer>
    </div>
</div>
</body>
</html>

sxtblog/templates/footer.html
<div class="outer">
    <div id="footer-info" class="inner"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
        ©叶子</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
        Powered by </font></font><a href="http://localhost:8000/#" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Hexo</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
        Theme by </font></font><a href="http://localhost:8000/#" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">BJSXT_B207班</font></font></a>
    </div>
</div>

sxtblog/templates/header.html
<div id="banner"></div>
    <div id="header-outer" class="outer">
        <div id="header-inner" class="inner">
            <nav id="main-nav">
                <a class="main-nav-link" href="{% url 'blog:index' %}"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">首页</font></font></a>
                <a class="main-nav-link" href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">归档</font></font></a>
                <a class="main-nav-link" href="{% url 'blog:about' %}" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">关于</font></font></a>
            </nav>
            <div class="d1">
                <form method="get" action="/search/">
                    <input type="text" name="q" placeholder=" 搜索">
                </form>
            </div>
        </div>
    </div>

sxtblog/templates/right.html
<!--分类-->
<div class="widget-wrap">
    <h3 class="widget-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">分类</font></font></h3>
    <div class="widget">
        <ul class="category-list">
            {% for category in cate_posts  %}
                <li class="category-list-item">
                    <a class="category-list-link" href="/category/{{ category.category }}"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ category.category__cname }}</font></font></a>
                    <span class="category-list-count"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ category.count }}</font></font></span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<!--归档-->
<div class="widget-wrap">
    <h3 class="widget-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">归档</font></font></h3>
    <div class="widget">
        <ul class="archive-list">
            {% for time in arc_posts %}
                <li class="archive-list-item">
                    <a class="archive-list-link" href="/archive/{{ time.0|date:'Y/m' }}"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ time.0|date:'Y年m月' }}</font></font></a>
                    <span class="archive-list-count"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ time.1 }}</font></font></span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<!--近期文章-->
<div class="widget-wrap">
    <h3 class="widget-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">近期文章</font></font></h3>
    <div class="widget">
        <ul>
            {% for blog in recent_posts %}
                <li>
                    <a href="/post/{{ blog.id }}" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ blog.title }}</font></font></a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="widget-wrap">
    <h3 class="widget-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">友情链接</font></font></h3>
    <div class="widget">
        <ul>
            <li>
                <a href="http://www.bjsxt.com/" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">尚学堂</font></font></a>
            </li>
            <li>
                <a href="http://www.sxt.cn/" target="_blank"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">速学堂</font></font></a>
            </li>
        </ul>
    </div>
</div>