myblog/article/urls.py
from django.conf.urls import url
from article import views

app_name = 'article'
urlpatterns = [
    url('^$', views.login, name='login'),
    url('^index/', views.index, name='index'),
    url('^about/', views.about, name='about'),
    url('^time/', views.time, name='time'),
    url('^info/', views.info, name='info'),
    url('^life/', views.life, name='life'),
    url(r'^search/$', views.search, name='search'),
    url('^add/', views.add, name='add'),
    url('^category/', views.category, name='category'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.static import serve
from myblog.settings import MEDIA_ROOT



urlpatterns = [
    url('admin/', admin.site.urls),
    url('^', include('article.urls', namespace='article')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),
    url(r'^search/', include('haystack.urls')),
]

myblog/account/models.py
from django.db import models


class User(models.Model):
    uname = models.CharField(max_length=20, unique=True)
    userpi = models.CharField(max_length=30, null=True, blank=True)
    pwd = models.CharField(max_length=20)
    userinfo = models.CharField(max_length=50, null=True)
    created = models.DateTimeField(auto_now_add=True)
    img = models.ImageField(upload_to='userimg', null=True)
    email = models.CharField(max_length=30, null=True)


    class Meta:
        db_table = 'users'

    def __str__(self):
        return self.uname

myblog/article/models.py
from django.db import models
from account.models import User
from tinymce.models import HTMLField


class Category(models.Model):
    cname = models.CharField(max_length=20, unique=True, verbose_name='分类')

    class Meta:
        db_table = 'category'
        verbose_name_plural = '分类'

    def __str__(self):
        return self.cname


class Tag(models.Model):
    tname = models.CharField(max_length=20, verbose_name='标签', unique=True)

    class Meta:
        db_table = 'tag'
        verbose_name_plural = '标签'

    def __str__(self):
        return self.tname


class Article(models.Model):
    uname = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    # 类别
    title = models.CharField(max_length=20, verbose_name='标题')
    content = HTMLField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类')
    creation_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    read_num = models.PositiveIntegerField(default=0, verbose_name='阅读量')
    collect_num = models.PositiveIntegerField(default=0, verbose_name='收藏量')
    img = models.ImageField(upload_to='articleimg', null=True, blank=True)
    # tag = models.ManyToManyField(Tag)
    isDelete = models.BooleanField(default=False)

    class Meta:
        db_table = 'article'
        verbose_name_plural = '博客'

    def __str__(self):
        return self.title

myblog/account/views.py
from django.shortcuts import render

# Create your views here.

myblog/article/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import *
from account.models import User
# import random
# from django.contrib.auth.models import User
# from django.contrib.auth.views import

# 全局用户名, 登录成功到主页时会自动设置为当前用户名 缺点：每次重启服务器得从主页进 否则会为None
uname = None


def handle():
    # 获取当前用户及其所有的文章
    user = User.objects.get(uname=uname)
    articles = user.article_set.all().order_by('id')
    return user,articles


def warp(func):
    def in_warp(request, *args, **kwargs):
        if request.session.has_key('uname'):
            global uname
            uname = request.session['uname']
            return func(request, *args, **kwargs)
        else:
            return redirect('/')
    return in_warp

@warp
def index(request):
    user, articles = handle()
    # 点击排行
    # order = articles.order_by('read_num')[:3]
    # 推荐文章
    # tuijian = articles[1:4]
    # articles = articles.order_by('creation_time')
    return render(request, 'index.html', {'articles': articles, 'user': user})


@warp
def life(request):
    user, articles = handle()
    pg = Paginator(articles, 7)
    num = request.GET.get('num', '1')
    page = pg.page(int(num))
    return render(request, 'life.html', {'articles': articles, 'user': user, 'page':page})

@warp
def info(request):
    user, articles = handle()
    # 根据用户名来找每一个用户的博客
    id = request.GET.get('id', '1')
    if request.session.has_key('search'):
        id = request.session['search']
        del request.session['search']
    if id == '1':
        article = user.article_set.first()
    else:
        article = user.article_set.get(pk=id)
    previou = user.article_set.filter(pk__lt=id).last()
    next = user.article_set.filter(pk__gt=id).first()
    return render(request, 'info.html', {'article': article, 'user': user, 'previou': previou, 'next': next, 'articles':articles })

@warp
def time(request):
    articles = Article.objects.filter(uname__uname=uname)
    return render(request, 'time.html', {'articles': articles})

@warp
def about(request):
    user, articles = handle()
    return render(request, 'about.html', {'user': user})


def search(request):
    from haystack.query import SearchQuerySet
    from haystack.query import SQ

    # 获取请求参数
    keywords = request.GET.get('q','')
    search_posts = SearchQuerySet().filter(SQ(title=keywords)|SQ(content=keywords))
    s_posts = []
    for s_p in search_posts:
        s_posts.append(s_p.object)
    return render(request,'archive.html',{'archive_posts':s_posts})


def login(request):
    if request.method == 'GET':
        if request.session.has_key('uname'):
            del request.session['uname']
        return render(request, 'login.html')
    else:
        uname = request.POST.get('uname', '')
        pwd = request.POST.get('pwd', '')
        if len(uname) >= 2 and len(pwd) >= 6:
            if User.objects.filter(uname=uname):
                if User.objects.get(uname=uname).pwd == pwd:
                    request.session['uname'] = uname
                    # request.session.set_expiry(0) #代表着关闭浏览器session过期
                    return redirect('/index/')
            else:
                    return redirect('/')
        return redirect('/')


# def register(request):
#     if request.method == 'GET':
#         return render(request, 'account/register.html')
#     else:
#         uname = request.POST.get('username', '')
#         pwd = request.POST.get('pwd', '')
#         if len(uname) >= 2 and len(pwd)>= 6:
#             if User.objects.filter(uname=uname):
#                 if User.objects.get(uname=uname).pwd == pwd:
#                     return redirect('/account/')
#             else:
#                 User.objects.create(uname=uname, pwd=pwd)
#                 return HttpResponse('注册成功')
#         return HttpResponse('注册失败')

@warp
def add(request):
    # 文本格式会导致布局紊乱
    # 要么修改文本格式 要么去index里调整显示方式
    if request.method == "GET":
        return render(request, 'add.html')
    else:
        title = request.POST.get('title')
        content = request.POST.get('hcontent')
        read = request.POST.get('read')
        collect = request.POST.get('collect')
        img = request.FILES.get('img')
        types = request.POST.get('type')
        Article.objects.create(
            uname=User.objects.get(uname=uname),
            title=title, content=content,
            read_num = read,
            collect_num=collect,
            category = Category.objects.get(cname=types),
            img = img
        )
        return redirect('/index/')


def category(request):
    category_name = request.GET.get('category')
    print(category_name)
    cate = Category.objects.get(cname=category_name)
    cates = cate.article_set.all()
    return render(request, 'category.html', {'cates': cates, 'cate': cate, 'articles':cates})

myblog/article/templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}

<article> 
  <!--banner begin-->
 <div class="picsbox"> 
  <div class="banner">
    <div id="banner" class="fader">
      <li class="slide" ><a href="/info/?id={{ articles0.id}}" target="_blank"><img src="{{ MEDIA_URL }}{{ articles.0.img }}"><span class="imginfo">{{ articles.0.title }}</span></a></li>
      <li class="slide" ><a href="/info/?id={{ articles1.id}}" target="_blank"><img src="{{ MEDIA_URL }}{{ articles.1.img }}"><span class="imginfo">{{ articles.1.title }}</span></a></li>
      <li class="slide" ><a href="/info/?id={{ articles2.id}}" target="_blank"><img src="{{ MEDIA_URL }}{{ articles.2.img }}"><span class="imginfo">{{ articles.2.title }}</span></a></li>
      <div class="fader_controls">
        <div class="page prev" data-target="prev">&lsaquo;</div>
        <div class="page next" data-target="next">&rsaquo;</div>
        <ul class="pager_list">
        </ul>
      </div>
    </div>
  </div>
  <!--banner end-->
  <div class="toppic">
    <li> <a href="https://www.csdn.net/" target="_blank"> <i><img src="{% static 'images/csdn.jpg' %}"></i>
      <h2>CSDN</h2>
      <span>外链</span> </a> </li>
    <li> <a href="https://www.djangoproject.com/" target="_blank"> <i><img src="{% static 'images/django.jpg' %}"></i>
      <h2>Django</h2>
      <span>技术</span> </a> </li>
  </div>
  </div>
  <div class="blank"></div>
  <!--blogsbox begin-->
  <div class="blogsbox">
    {% for article in articles|dictsortreversed:"creation_time"|slice:":7" %}
    <div class="blogs" data-scroll-reveal="enter bottom over 1s"  style="overflow: hidden;text-overflow:ellipsis">
      <h3 class="blogtitle"><a href="/info/?id={{ article.id}}" target="_blank">{{ article.title }}</a></h3>
      <span class="blogpic"><a href="/info/?id={{ article.id}}" title=""><img src="{{ MEDIA_URL }}{{ article.img }}" alt=""></a></span>
        <p class="blogtext">{{ article.content|safe|truncatewords:"2" }}</p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="{% url 'article:about' %}">{{ user.uname }}</a></li>
          <li class="lmname"><a href="/category/?category={{ article.category.cname }}">{{ article.category.cname }}</a></li>
          <li class="timer">{{ article.creation_time }}</li>
          <li class="view"><span>{{ article.read_num }}</span>已阅读</li>
          <li class="like">{{ article.collect_num }}</li>
        </ul>
      </div>
    </div>
    {% endfor %}

  </div>

{% include 'tebietuijian.html' %}

</article>

{% endblock content %}

myblog/article/templates/info.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<article>
  <h1 class="t_nav"><span>您现在的位置是：首页 > 内容页</span><a href="{% url 'article:index' %}" class="n1">网站首页</a><a href="#" class="n2">内容页</a></h1>
  <div class="infosbox">
    <div class="newsview">
      <h3 class="news_title">{{ article.title }}</h3>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="#">{{ user.uname }}</a></li>
          <li class="lmname"><a href="#">{{ article.category.cname }}</a></li>
          <li class="timer">{{ article.creation_time }}</li>
          <li class="view">{{ article.read_num }}已阅读</li>
          <li class="like">{{ article.collect_num }}</li>
        </ul>
      </div>
      <div class="tags"><a href="#" target="_blank">个人博客</a> &nbsp; <a href="/category/?category={{ article.category.cname }}" target="_blank">{{ article.category.cname }}</a></div>
      <div class="news_about"><strong>简介</strong>个人博客</div>
      <div class="news_con">
        {{ article.content|safe }}
      </div>
    </div>

    <div class="nextinfo">
        {% if previou %}
      <p>上一篇：<a href="/info/?id={{ previou.id }}">{{ previou.title }}</a></p>
        {% endif %}
     {% if next %}
      <p>下一篇：<a href="/info/?id={{ next.id }}">{{ next.title }}</a></p>
    {% endif %}
    </div>

    <div class="otherlink">
      <h2>相关文章</h2>
      <ul>
{#        {% for i in  %}#}
        <li><a href="#" title="">个人博客</a></li>
{#        endfor#}
      </ul>
    </div>
  </div>

{% include 'tebietuijian.html' %}
</article>

{% endblock content %}

myblog/article/templates/life.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<div class="pagebg sh"></div>
<div class="container">
  <h1 class="t_nav"><span>慢生活，不是懒惰，放慢速度不是拖延时间，而是让我们在生活中寻找到平衡。</span><a href="{% url 'article:index' %}" class="n1">网站首页</a><a href="#" class="n2">慢生活</a></h1>
  <!--blogsbox begin-->
  <div class="blogsbox">
    {% for article in page %}
    <div class="blogs" data-scroll-reveal="enter bottom over 1s"  style="overflow: hidden;text-overflow:ellipsis">
      <h3 class="blogtitle"><a href="/info/?id={{ article.id}}" target="_blank">{{ article.title }}</a></h3>
      <span class="blogpic"><a href="/info/?id={{ article.id}}" title=""><img src="{{ MEDIA_URL }}{{ article.img }}" alt=""></a></span>
        <p class="blogtext">{{ article.content|safe|truncatewords:"2" }}</p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="#">{{ user.uname }}</a></li>
          <li class="lmname"><a href="#">{{ article.category.cname }}</a></li>
          <li class="timer">{{ article.creation_time }}</li>
          <li class="view"><span>{{ article.read_num }}</span>已阅读</li>
          <li class="like">{{ article.collect_num }}</li>
        </ul>
      </div>
    </div>
    {% endfor %}
    
    <div class="pagelist">
        <a title="Total record" href="/life/?num=1">&nbsp;
            <b>首页</b>
        </a>
        {% for i in page.paginator.page_range %}
        <a href="/life/?num={{ i }}">{{ i }}</a>&nbsp;
        {% endfor %}
        {% if page.has_next %}
        <a href="/life/?num={{ page.next_page_number }}">下一页</a>&nbsp;
        {% endif %}
        <a href="/life/?num={{ page.paginator.num_pages  }}">尾页</a></div>
  </div>
  <!--blogsbox end-->
 {% include 'tebietuijian.html' %}
</div>
{% endblock content %}

myblog/article/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'js/jquery.min.js' %}"></script>
</head>
<body>
<script>$(document).ready(function(c) {
	$('.close').on('click', function(c){
		$('.login-form').fadeOut('slow', function(c){
	  		$('.login-form').remove();
		});
	});	  
});
</script>
 <!--SIGN UP-->
 <h1>Login</h1>
<div class="login-form">
	<div class="close"> </div>
		<div class="head-info">
			<label class="lbl-1"> </label>
			<label class="lbl-2"> </label>
			<label class="lbl-3"> </label>
		</div>
			<div class="clear"> </div>
	<div class="avtar">
		<img src="{% static 'images/avtar.png' %}" />
	</div>
			<form action="{% url 'article:login' %}" method="post">
                {% csrf_token %}
					<input type="text" class="text" placeholder="Username" name="uname" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Username';}" >
						<div class="key">
					<input type="password" placeholder="password"="Password" name="pwd" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}">
						</div>
                <input type="submit" value="Login" >
			</form>
	<div class="signin">
	</div>
</div>
 <div class="copy-rights">
					<p>Copyright &copy; 2015.Company name All rights reserved.More Templates <a href="#" target="_blank" title="">xxxxx</a> - Collect from <a href="http://www.cssmoban.com/" title="xxxxx" target="_blank">xxxxx</a></p>
			</div>

</body>
</html>

myblog/templates/footer.html
<footer>
  <p>Design by <a href="#" target="_blank">个人博客</a> <a href="/">##########</a></p>
</footer>
<a href="#" class="cd-top">Top</a>

myblog/templates/header.html
<header>
    <!--menu begin-->
    <div class="menu">
        <nav class="nav" id="topnav">
            <h1 class="logo"><a href="#">博客</a></h1>
            <li><a href="{% url 'article:index' %}">网站首页</a> </li>
            <li><a href="{% url 'article:about' %}">关于我</a> </li>
            <li><a href="{% url 'article:life' %}">慢生活</a>
                <ul class="sub-nav">
                    <li><a href="https://www.python.org/">Python</a></li>
                    <li><a href="https://www.baidu.com/">百度</a></li>
                    <li><a href="https://www.csdn.net/">CSDN</a></li>
                    <li><a href="https://github.com/">GitHub</a></li>
                </ul>
            </li>
            <li><a href="{% url 'article:add' %}">新增博客</a>
            <li><a href="{% url 'article:time' %}">时间轴</a> </li>
            <li><a href="{% url 'article:info' %}">内容页</a> </li>
            <li><a href="/">退出登录</a> </li>
            <!--search begin-->
            <div id="search_bar" class="search_bar">
                <form  id="searchform" action="{% url 'article:search' %}" name="searchform" method="get">
                    <input class="input" placeholder="想搜点什么呢..." type="text" name="q" id="keyboard">
                    <span class="search_ico"></span>
                </form>
            </div>
            <!--search end-->
        </nav>
    </div>
    <!--menu end-->
    <!--mnav begin-->
    <div id="mnav">
        <h2><a href="#" class="mlogo">博客</a><span class="navicon"></span></h2>
        <dl class="list_dl">
            <dt class="list_dt"> <a href="{% url 'article:index' %}">网站首页</a> </dt>
            <dt class="list_dt"> <a href="{% url 'article:about' %}">关于我</a> </dt>
            <dt class="list_dt"> <a href="#">慢生活</a> </dt>
            <dd class="list_dd">
                <ul>
                    <li><a href="https://www.python.org/">Python</a></li>
                    <li><a href="https://www.baidu.com/">百度</a></li>
                    <li><a href="https://www.csdn.net/">CSDN</a></li>
                    <li><a href="https://github.com/">GitHub</a></li>
                </ul>
            </dd>
            <dt class="list_dt"> <a href="{% url 'article:time' %}">时间轴</a> </dt>
            <dt class="list_dt"> <a href="{% url 'article:info' %}">内容页</a> </dt>
        </dl>
    </div>
    <!--mnav end-->
</header>

myblog/templates/wait/index.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<meta charset="utf-8">
<title>首页_{{ user.uname }}的博客</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static  'css/base.css'%}" rel="stylesheet">
<link href="{% static  'css/index.css'%}" rel="stylesheet">
<link href="{% static  'css/m.css'%}" rel="stylesheet">
<script src="{% static  'js/jquery.min.js'%}" type="text/javascript"></script>
<script src="{% static  'js/jquery.easyfader.min.js'%}"></script>
<script src="{% static  'js/scrollReveal.js'%}"></script>
<script src="{% static  'js/common.js'%}"></script>
<!--[if lt IE 9]>
<script src="{% static 'js/modernizr.js' %}"></script>
<![endif]-->
</head>
<body>
<header>
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="#">博客</a></h1>
      <li><a href="{% url 'article:index' %}">网站首页</a> </li>
      <li><a href="{% url 'article:about' %}">关于我</a> </li>
      <li><a href="{% url 'article:life' %}">慢生活</a>
        <ul class="sub-nav">
          <li><a href="/life/">日记</a></li>
          <li><a href="/life/">欣赏</a></li>
          <li><a href="/life/">程序人生</a></li>
          <li><a href="/life/">经典语录</a></li>
        </ul>
      </li>
      <li><a href="{% url 'article:time' %}">时间轴</a> </li>
      <li><a href="{% url 'article:info' %}">内容页</a> </li>
        <li><a href="/">退出登录</a> </li>
      <li><a href="/">★</a> </li>
      <!--search begin-->
      <div id="search_bar" class="search_bar">
        <form  id="searchform" action="[!--news.url--]e/search/index.php" method="post" name="searchform">
          <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
          <input type="hidden" name="show" value="title" />
          <input type="hidden" name="tempid" value="1" />
          <input type="hidden" name="tbname" value="news">
          <input type="hidden" name="Submit" value="搜索" />
          <span class="search_ico"></span>
        </form>
      </div>
      <!--search end-->
    </nav>
  </div>
  <!--menu end-->
  <!--mnav begin-->
  <div id="mnav">
    <h2><a href="#" class="mlogo">博客</a><span class="navicon"></span></h2>
    <dl class="list_dl">
      <dt class="list_dt"> <a href="{% url 'article:index' %}">网站首页</a> </dt>
      <dt class="list_dt"> <a href="{% url 'article:about' %}">关于我</a> </dt>
      <dt class="list_dt"> <a href="#">慢生活</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="/life/">日记</a></li>
          <li><a href="/life/">欣赏</a></li>
          <li><a href="/life/">程序人生</a></li>
          <li><a href="/life/">经典语录</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="{% url 'article:time' %}">时间轴</a> </dt>
      <dt class="list_dt"> <a href="{% url 'article:info' %}">内容页</a> </dt>
    </dl>
  </div>
  <!--mnav end-->
</header>
<article> 
  <!--banner begin-->
 <div class="picsbox"> 
  <div class="banner">
    <div id="banner" class="fader">
      <li class="slide" ><a href="/" target="_blank"><img src="{{ MEDIA_URL }}{{ articles.0.img }}"><span class="imginfo">{{ articles.0.title }}</span></a></li>
      <li class="slide" ><a href="/" target="_blank"><img src="{{ MEDIA_URL }}{{ articles.1.img }}"><span class="imginfo">{{ articles.1.title }}</span></a></li>
      <li class="slide" ><a href="/" target="_blank"><img src="{{ MEDIA_URL }}{{ articles.2.img }}"><span class="imginfo">{{ articles.2.title }}</span></a></li>
      <div class="fader_controls">
        <div class="page prev" data-target="prev">&lsaquo;</div>
        <div class="page next" data-target="next">&rsaquo;</div>
        <ul class="pager_list">
        </ul>
      </div>
    </div>
  </div>
  <!--banner end-->
  <div class="toppic">
    <li> <a href="/" target="_blank"> <i><img src="{% static 'images/toppic01.jpg' %}"></i>
      <h2>别让这些闹心的套路，毁了你的网页设计!</h2>
      <span>图片</span> </a> </li>
    <li> <a href="/" target="_blank"> <i><img src="{% static 'images/zd01.jpg' %}"></i>
      <h2>个人博客，属于我的小世界！</h2>
      <span>图片</span> </a> </li>
  </div>
  </div>
  <div class="blank"></div>
  <!--blogsbox begin-->
  <div class="blogsbox">
    {% for article in articles %}
    <div class="blogs" data-scroll-reveal="enter bottom over 1s"  style="overflow: hidden;text-overflow:ellipsis">
      <h3 class="blogtitle"><a href="/info/?id={{ article.id}}" target="_blank">{{ article.title }}</a></h3>
{#      <span class="blogpic"><a href="/info/?id={{ article.id}}" title=""><img src="{% static 'images/toppic01.jpg' %}" alt=""></a></span>#}
      <span class="blogpic"><a href="/info/?id={{ article.id}}" title=""><img src="{{ MEDIA_URL }}{{ article.img }}" alt=""></a></span>
        <p class="blogtext">{{ article.content|safe|truncatewords:"3" }}</p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="#">{{ user.uname }}</a></li>
          <li class="lmname"><a href="#">{{ article.category.cname }}</a></li>
          <li class="timer">{{ article.creation_time }}</li>
          <li class="view"><span>{{ article.read_num }}</span>已阅读</li>
          <li class="like">{{ article.collect_num }}</li>
        </ul>
      </div></div>
    {% endfor %}

  </div>
  <!--blogsbox end-->
  <div class="sidebar">
    <div class="zhuanti">
      <h2 class="hometitle">特别推荐</h2>

      <ul>

        {% for article in articles %}
            {% if forloop.counter < 4 %}
        <li> <i><img src="{{ MEDIA_URL }}{{ article.img }}"></i>
          <p>{{ article.title}}<span><a href="/info/?id={{ article.id}}">{{ article.category.cname }}</a></span> </p>
        </li>
            {% endif %}
        {% endfor %}
      </ul>

    </div>
    <div class="tuijian">
      <h2 class="hometitle">推荐文章</h2>
      <ul class="tjpic">
        <i><img src="{% static 'images/bi01.jpg' %}"></i>
        <p><a href="#">待填写标题</a></p>
      </ul>

      <ul class="sidenews">
        {% for article in articles %}
            {% if forloop.counter < 4 %}
        <li> <i><img src="{{ MEDIA_URL }}{{ article.img }}"></i>
          <p><a href="/info/?id={{ article.id}}">{{ article.title }}</a></p>
          <span>{{ article.creation_time }}</span> </li>
            {% endif %}
        {% endfor %}
      </ul>
    </div>
    <div class="tuijian">
      <h2 class="hometitle">点击排行</h2>

      <ul class="tjpic">
        <i><img src="{% static 'images/toppic01.jpg' %}"></i>
        <p><a href="/">请填写这些标题</a></p>
      </ul>

      <ul class="sidenews">
        {% for i in articles %}
          {% if forloop.counter < 4 %}
        <li> <i><img src="{{ MEDIA_URL }}{{ i.img }}"></i>
          <p><a href="/">{{ i.title }}</a></p>
          <span>{{ i.creation_time }}</span> </li>
            {% endif %}
        {% endfor %}
      </ul>
    </div>
    <div class="cloud">
      <h2 class="hometitle">标签云</h2>
      <ul>
        <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
      </ul>
    </div>
  </div>
</article>
<footer>
  <p>Design by <a href="#" target="_blank">个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>